{% set name = "findorb" %}
{% set version = "0.0.20220824" %}
{% set sha_findorb = "c5d8d5806faaf96d3eb26a2d62d07bbe3d446b82" %}
{% set sha_lunar = "05c54ba6655daba25fd80c91e7ddae7fa48e409e" %}
{% set sha_jpl_eph = "6716858ef2630b5a1bfde42248d9ef3fa3b22aee" %}
{% set sha_sat_code = "47e5c69c3bb32e86d3f2d2461301ab8d24c0d5d9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/Bill-Gray/find_orb/archive/{{ sha_findorb }}.tar.gz
    sha256: 6400f1b8b9028bf5d8d7b77715c6f8af2e7d41734b862ba8d692acc9e6830f04
    folder: sources/find_orb
  - url: https://github.com/Bill-Gray/lunar/archive/{{ sha_lunar }}.tar.gz
    sha256: 0158ffcbc395eae35d815dd8a8bd8eb47221c46b82a359de0d7a0803a9ec7579
    folder: sources/lunar
  - url: https://github.com/Bill-Gray/jpl_eph/archive/{{ sha_jpl_eph }}.tar.gz
    sha256: 79f73561f040acff7f2397b2bed856ff0e98f795bc8d70d1e96f9863a406bb82
    folder: sources/jpl_eph
  - url: https://github.com/Bill-Gray/sat_code/archive/{{ sha_sat_code }}.tar.gz
    sha256: 6b0cf5533ebeeb3d290cbbd8737d230e54b238e52d293a74031f28edb0497aea
    folder: sources/sat_code

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - curl
    - git
  host:
    - cpp-filesystem  # [osx]
    - ncurses
  run:
    - ncurses
    - findorb-data-de430t

test:
  files:
    - single.psv
    - fo.expected.out

about:
  home: https://github.com/Bill-Gray/find_orb
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: sources/find_orb/LICENSE
  summary: 'Orbit determination from observations'
  description: |
    Find_Orb can take a set of observations of an asteroid, comet, or natural or artificial satellite,
    given in the MPC (Minor Planet Center) format, the newer ADES astrometric format,
    and/or the NEODyS or AstDyS formats, and find the corresponding orbit.
  doc_url: https://www.projectpluto.com/find_orb.htm
  dev_url: https://github.com/Bill-Gray/find_orb

extra:
  recipe-maintainers:
    - mjuric
    - moeyensj
    - caditi97
