{% set name = "findorb" %}
{% set version = "0.0.20220506" %}
{% set sha_findorb = "343e680040ee2bde5d17ff413cc80809622b7463" %}
{% set sha_lunar = "021806dc0983ad6f028504da9e95c0ff4a6f5852" %}
{% set sha_jpl_eph = "3911106829157e70dada93bf5f0fcaaf0582df76" %}
{% set sha_sat_code = "47e5c69c3bb32e86d3f2d2461301ab8d24c0d5d9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/Bill-Gray/find_orb/archive/{{ sha_findorb }}.tar.gz
    sha256: 6f275d245c5088bbde041f6c58f3ca25055b3c07917c4f9e6a6a6f008e439e6c
    folder: sources/find_orb
  - url: https://github.com/Bill-Gray/lunar/archive/{{ sha_lunar }}.tar.gz
    sha256: f9a022f12e846f3a46340e5537c8bc9e4b0763d130ac876ccf5bf9d7fc9b48d8
    folder: sources/lunar
  - url: https://github.com/Bill-Gray/jpl_eph/archive/{{ sha_jpl_eph }}.tar.gz
    sha256: 98adc4f262db34dae40bbbdc3763c9d31fc98c96a9162d45eae230e6c3d530b7
    folder: sources/jpl_eph
  - url: https://github.com/Bill-Gray/sat_code/archive/{{ sha_sat_code }}.tar.gz
    sha256: 6b0cf5533ebeeb3d290cbbd8737d230e54b238e52d293a74031f28edb0497aea
    folder: sources/sat_code

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - curl
    - git
  host:
    - cpp-filesystem  # [osx]
    - ncurses
  run:
    - ncurses
    - findorb-data-de430t

test:
  files:
    - single.psv
    - fo.expected.out

about:
  home: https://github.com/Bill-Gray/find_orb
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: sources/find_orb/LICENSE
  summary: 'Orbit determination from observations'
  description: |
    Find_Orb can take a set of observations of an asteroid, comet, or natural or artificial satellite,
    given in the MPC (Minor Planet Center) format, the newer ADES astrometric format,
    and/or the NEODyS or AstDyS formats, and find the corresponding orbit.
  doc_url: https://www.projectpluto.com/find_orb.htm
  dev_url: https://github.com/Bill-Gray/find_orb

extra:
  recipe-maintainers:
    - mjuric
    - moeyensj
