conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'

# conda-forge.yml
# Enable builds for all common conda-forge architectures:
#   - Linux x86_64
#   - Linux aarch64
#   - macOS x86_64
#   - macOS arm64

build_platform:
  linux_64: linux_64
  linux_aarch64: linux_aarch64
  osx_64: osx_64
  osx_arm64: osx_arm64

provider:
  linux_64: azure
  linux_aarch64: azure
  osx_64: azure
  osx_arm64: azure
